apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-service-config
  namespace: todo
data:
  SERVER_PORT: "8081"
  POSTGRES_URL: jdbc:postgresql://10.0.0.1:5432/todo_db
  RABBITMQ_HOST: "10.0.0.1"
  RABBITMQ_PORT: "5672"
  RABBITMQ_EXCHANGE: platform.notifications
  RABBITMQ_NOTIFICATION_EVENTS_ROUTINGKEY: notification.event
  RABBITMQ_NOTIFICATION_CANCEL_ROUTINGKEY: notification.cancel
  KEYCLOAK_ISSUER_URI: https://keycloak.hadiubaidillah.com/realms/todo
  KEYCLOAK_JWKS_URI: https://keycloak.hadiubaidillah.com/realms/todo/protocol/openid-connect/certs
  EUREKA_HOSTNAME: discovery-server
  REDIS_HOST: "10.0.0.1"
  REDIS_PORT: "6379"
  ZIPKIN_URL: http://10.0.0.1:9411
