apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: todo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:26.5.3
          args: ["start-dev", "--import-realm"]
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: keycloak-secret
          env:
            - name: KC_DB
              value: postgres
            - name: KC_DB_URL
              value: jdbc:postgresql://postgres:5432/postgres
            - name: KC_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: KC_HOSTNAME
              value: keycloak.hadiubaidillah.com
            - name: KC_PROXY_HEADERS
              value: xforwarded
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 9000
            initialDelaySeconds: 30
            periodSeconds: 10
