apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
  namespace: todo
type: Opaque
stringData:
  KC_BOOTSTRAP_ADMIN_USERNAME: <your-keycloak-admin-username>
  KC_BOOTSTRAP_ADMIN_PASSWORD: <your-keycloak-admin-password>
