apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: microservices-platform

resources:
  - namespace.yaml

  # Secrets
  - secrets/postgres-secret.yaml
  - secrets/rabbitmq-secret.yaml
  - secrets/keycloak-secret.yaml
  - secrets/mail-secret.yaml

  # ConfigMaps
  - configmaps/discovery-config.yaml
  - configmaps/gateway-config.yaml
  - configmaps/notification-service-config.yaml
  - configmaps/todo-service-config.yaml
  - configmaps/frontend-config.yaml

  # Deployments
  - deployments/postgres.yaml
  - deployments/rabbitmq.yaml
  - deployments/keycloak.yaml
  - deployments/discovery-server.yaml
  - deployments/gateway-server.yaml
  - deployments/notification-service.yaml
  - deployments/todo-service.yaml
  - deployments/frontend.yaml

  # Services
  - services/postgres-svc.yaml
  - services/rabbitmq-svc.yaml
  - services/keycloak-svc.yaml
  - services/discovery-svc.yaml
  - services/gateway-svc.yaml
  - services/notification-svc.yaml
  - services/todo-svc.yaml
  - services/frontend-svc.yaml

  # Ingress
  - ingress.yaml
