global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert-rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "gateway-server"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["gateway-server:8080"]

  - job_name: "todo-service"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["todo-service:8081"]

  - job_name: "notification-service"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["notification-service:8082"]
