apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - configmaps/discovery-config.yaml
  - configmaps/gateway-config.yaml
  - configmaps/todo-service-config.yaml
  - configmaps/notification-service-config.yaml
  - configmaps/frontend-config.yaml
