spring:
  application:
    name: tasks-discovery-server

eureka:
  instance:
    hostname: localhost
  dashboard:
    enabled: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
server:
  port: ${SERVER_PORT:8761}
