apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-server
  namespace: todo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-server
  template:
    metadata:
      labels:
        app: gateway-server
    spec:
      imagePullSecrets:
        - name: harbor-secret
      containers:
        - name: gateway-server
          image: harbor.hadiubaidillah.com/todo/gateway-server:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: gateway-config
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: REDIS_PASSWORD
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 15
