apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
  namespace: todo
data:
  SERVER_PORT: "8080"
  EUREKA_HOSTNAME: discovery-server
  CORS_ALLOWED_ORIGINS: https://todo.hadiubaidillah.com
  KEYCLOAK_ISSUER_URI: http://keycloak:8080/realms/todo
  KEYCLOAK_JWKS_URI: http://keycloak:8080/realms/todo/protocol/openid-connect/certs
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  ZIPKIN_URL: http://zipkin:9411
