server:
  port: ${SERVER_PORT:8082}

spring:
  application:
    name: notification-service
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/platform_notification_db}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
  mail:
    host: ${MAIL_SMTP_HOST:smtp.example.com}
    port: ${MAIL_SMTP_PORT:587}
    username: ${MAIL_SMTP_USERNAME:}
    password: ${MAIL_SMTP_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  cache:
    type: redis
    redis:
      time-to-live: 300000

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8083/realms/todo}
          jwk-set-uri: ${KEYCLOAK_JWKS_URI:http://localhost:8083/realms/todo/protocol/openid-connect/certs}

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOSTNAME:localhost}:8761/eureka/
  instance:
    prefer-ip-address: true

rabbitmq:
  exchange: ${RABBITMQ_EXCHANGE:platform.notifications}
  notification-events:
    queue: ${RABBITMQ_NOTIFICATION_EVENTS_QUEUE:notification.events}
    routing-key: ${RABBITMQ_NOTIFICATION_EVENTS_ROUTINGKEY:notification.event}
  notification-email:
    queue: ${RABBITMQ_NOTIFICATION_EMAIL_QUEUE:notification.email}
    routing-key: ${RABBITMQ_NOTIFICATION_EMAIL_ROUTINGKEY:notification.email}
  notification-cancel:
    queue: ${RABBITMQ_NOTIFICATION_CANCEL_QUEUE:notification.cancel}
    routing-key: ${RABBITMQ_NOTIFICATION_CANCEL_ROUTINGKEY:notification.cancel}

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

management:
  health:
    mail:
      enabled: false
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics,circuitbreakers
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL:http://localhost:9411}/api/v2/spans
  metrics:
    tags:
      application: ${spring.application.name}
