apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: todo
resources:
  - namespace.yaml
  - secrets/harbor-secret.yaml
  - secrets/postgres-secret.yaml
  - secrets/rabbitmq-secret.yaml
  - secrets/redis-secret.yaml
  - secrets/mail-secret.yaml
  - deployments/discovery-server.yaml
  - deployments/gateway-server.yaml
  - deployments/todo-service.yaml
  - deployments/notification-service.yaml
  - deployments/frontend.yaml
  - services/discovery-svc.yaml
  - services/gateway-svc.yaml
  - services/todo-svc.yaml
  - services/notification-svc.yaml
  - services/frontend-svc.yaml
  - ingress.yaml
