apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: todo
type: Opaque
stringData:
  RABBITMQ_DEFAULT_USER: <your-rabbitmq-username>
  RABBITMQ_DEFAULT_PASS: <your-rabbitmq-password>
